name: e2e-Templum/govulncheck-action
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  vulcheck_1:
    name: checks working-directory provided with `/*`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: |
            govulncheck-action/app1
      - name: Scan for Vulnerabilities in Code
        uses: Templum/govulncheck-action@0eeca9d81f01facc00829cc99a14e44ce59ce80f # v1.0.2
        with:
          working-directory: /govulncheck-action/app1
          go-version: 1.23.1
          skip-upload: true
      - name: Upload vulncheck report
        uses: github/codeql-action/upload-sarif@1245696032ecf7d39f87d54daa406e22ddf769a8
        with:
          sarif_file: "./govulncheck-action/app1/govulncheck-report.sarif"
  vulcheck_2:
    name: checks working-directory provided with `./*`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: |
            govulncheck-action/app1
      - name: Scan for Vulnerabilities in Code
        uses: Templum/govulncheck-action@0eeca9d81f01facc00829cc99a14e44ce59ce80f # v1.0.2
        with:
          working-directory: ./govulncheck-action/app1
          go-version: 1.23.1
  vulcheck_3:
    name: checks with empty working-directory (should use default)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: mv govulncheck-action/app1/* ./
      - run: ls -la
      - name: Scan for Vulnerabilities in Code
        uses: Templum/govulncheck-action@0eeca9d81f01facc00829cc99a14e44ce59ce80f # v1.0.2
        with:
          go-version: 1.23.1
