name: e2e-Templum/govulncheck-action
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  vulcheck_1:
    name: checks working-directory provided with `/*`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: |
            govulncheck-action/app1
      - name: Scan for Vulnerabilities in Code
        uses: Templum/govulncheck-action@1934c7d061220d2d812adb75349d36ce6af4fa82
        with:
          working-directory: /govulncheck-action/app1
          go-version: 1.23.1
  vulcheck_2:
    name: checks working-directory provided with `./*`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: |
            govulncheck-action/app1
      - name: Scan for Vulnerabilities in Code
        uses: Templum/govulncheck-action@1934c7d061220d2d812adb75349d36ce6af4fa82
        with:
          working-directory: ./govulncheck-action/app1
          go-version: 1.23.1
  vulcheck_3:
    name: checks with empty working-directory (should use default)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: |
            govulncheck-action/app1
      - run: mv ./govulncheck-action/app1/* ./../../ # we move it to make it work.
      - run: ls -la
      - name: Scan for Vulnerabilities in Code
        uses: Templum/govulncheck-action@1934c7d061220d2d812adb75349d36ce6af4fa82
        with:
          go-version: 1.23.1
